branches:
  - master

matrix:
  include:
    - language: node_js
      node_js:
        - "stable"

      before_script:
        - cd ./src/environments
        - mv environment.ts environment.temp.ts
        - mv environment.prod.ts environment.ts
        - cd ../..

      script:
        - npm run build

      after_success:
        - cd ./dist

      deploy:
        skip_cleanup: true
        provider: heroku
        api_key:
          secure: 901bd999-6462-47eb-8b0e-d396dee67b94
        app: zvdo74-test-angular

    - language: node_js

      node_js:
        - "stable"

      # services:
      #   - mongodb
      #   - neo4j

      before_install:
        - cd ./api

      # before_script:
      #   - sleep 15

      # after_succes:
      #   - npm run cover
      #   - npm run coveralls

      deploy:
        provider: heroku
        api_key:
          secure: 901bd999-6462-47eb-8b0e-d396dee67b94
        app: zvdo74-test-api
